spring:
  datasource:
    url: jdbc:mysql://14.32.21.48:3306/works?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 287285986189-056lua02ael3eog7es7vm52h27ippmr3.apps.googleusercontent.com
            client-secret: czeFaemP9EjyFkQCAprSQLha
            redirect-uri: http://localhost:8080/oauth2/callback/google
            scope:
              - email
              - profile
  flyway:
    enabled: false

app:
  auth:
    tokenSecret: 92D696C9003AAB3DEA458429B2BA4281BA
    tokenExpirationMsec: 864000000
  oauth2:
      authorizedRedirectUris:
        - http://localhost:8080/oauth2/redirect
        - myandroidapp://oauth2/redirect
        - myiosapp://oauth2/redirect

logging:
  level:
    kr:
      co:
        tabling:
          works: debug
    org:
      springframework:
        web: debug
        security: debug



